apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: saagie
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/saagie/kubectl-saagie/releases/download/v0.1.0/saagie_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./saagie"
      to: "."
    - from: LICENSE
      to: "."
    bin: "saagie"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/saagie/kubectl-saagie/releases/download/v0.1.0/saagie_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./saagie"
      to: "."
    - from: LICENSE
      to: "."
    bin: "saagie"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/saagie/kubectl-saagie/releases/download/v0.1.0/saagie_windows_amd64.zip
    sha256: ""
    files:
    - from: "/saagie.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "saagie.exe"
  shortDescription: A new plugin
  homepage: https://github.com/saagie/kubectl-saagie
  caveats: |
    Usage:
      $ kubectl saagie

    For additional options:
      $ kubectl saagie --help
      or https://github.com/saagie/kubectl-saagie/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
